# Generated by Django 3.2.16 on 2023-02-18 19:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Contacts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(max_length=300, verbose_name="Адрес")),
                (
                    "phone_number",
                    models.CharField(max_length=11, verbose_name="Номер телефона"),
                ),
                (
                    "tg_link",
                    models.CharField(max_length=300, verbose_name="Ссылка на телеграм"),
                ),
                (
                    "vk_link",
                    models.CharField(max_length=300, verbose_name="Ссылка в вк"),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Эл.почта")),
            ],
        ),
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(max_length=150, verbose_name="Название компании"),
                ),
                ("start_date", models.DateField(verbose_name="Дата начала работы")),
                ("finish_date", models.DateField(verbose_name="Дата окончания работы")),
                (
                    "job_results",
                    models.CharField(max_length=300, verbose_name="Результаты работы"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Employer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(max_length=150, verbose_name="Название компании"),
                ),
                (
                    "staff_quantity",
                    models.PositiveIntegerField(verbose_name="Количество сотрудников"),
                ),
                ("city", models.CharField(max_length=50, verbose_name="Город")),
                ("about", models.CharField(max_length=2000, verbose_name="О компании")),
                ("is_employer", models.BooleanField(default=True)),
                (
                    "contacts",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employer_contacts",
                        to="accounts.contacts",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employer",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Applicant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "patronymic",
                    models.CharField(max_length=150, verbose_name="Отчество"),
                ),
                ("is_employer", models.BooleanField()),
                (
                    "contacts",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="applicant_contacts",
                        to="accounts.contacts",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applicant",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "work_experience",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="experience",
                        to="accounts.experience",
                    ),
                ),
            ],
        ),
    ]
