# Generated by Django 3.2.16 on 2023-02-21 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20230221_1339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='work_experience',
        ),
        migrations.AddField(
            model_name='experience',
            name='applicant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='experience', to='accounts.applicant'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='applicant',
            name='is_employer',
            field=models.BooleanField(default=False),
        ),
    ]
