# Generated by Django 3.2.16 on 2023-02-26 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_auto_20230222_1423"),
    ]

    operations = [
        migrations.AlterField(
            model_name="experience",
            name="applicant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="experience",
                to="accounts.applicant",
                verbose_name="Соискатель",
            ),
        ),
    ]
