# Generated by Django 3.2.16 on 2023-02-21 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='feedback',
            constraint=models.UniqueConstraint(fields=('vacancy', 'applicant'), name='unique_feedback'),
        ),
    ]
