# Generated by Django 3.2.16 on 2023-02-22 11:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vacancies", "0002_feedback_unique_feedback"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="feedback",
            options={"verbose_name": "Отклик", "verbose_name_plural": "Отклики"},
        ),
        migrations.AlterModelOptions(
            name="vacancy",
            options={
                "ordering": ("created",),
                "verbose_name": "Вакансия",
                "verbose_name_plural": "Вакансии",
            },
        ),
        migrations.AddField(
            model_name="vacancy",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Дата создания",
            ),
            preserve_default=False,
        ),
    ]
