# Generated by Django 3.2.16 on 2023-02-26 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vacancies", "0003_auto_20230222_1423"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="feedback",
            options={},
        ),
        migrations.RemoveConstraint(
            model_name="feedback",
            name="unique_feedback",
        ),
    ]
